-- ═══════════════════════════════════════════════════════════════════════════════
-- Session 2 + 3 — final estimation, invoice, customer approval, payment
--
-- What this adds, against the agreed flow:
--
--   partner submits FINAL estimation (initial vs final, per panel)
--        → invoice auto-generated as a DRAFT
--   admin checks the job        → invoice awaiting_release
--   admin releases the invoice  → invoice released  + job → 3_inspected
--                                  (customer notified: mailer + WhatsApp)
--   customer approves           → invoice approved  (awaiting payment)
--   customer declines           → invoice declined  + job → 0_cancelled
--                                  (partner + admin notified, delivery scheduled)
--   payment succeeds            → invoice paid      + job → 4_paid
--
-- Design notes that matter:
--
--  * repair_jobs.status is UNCHANGED. repair_jobs_status_check is load-bearing —
--    three customer/ops screens and the stepper derive their stage from it — so
--    approval is modelled as invoice state, not a new job status. The job only
--    moves at the two points the existing machine already has: 3_inspected when
--    the invoice is issued to the customer, 4_paid when it is paid.
--
--  * validate_status_transition() is a pass-through (it returns NEW in every
--    branch). Nothing enforces order at the trigger level, so every RPC here
--    states its own precondition explicitly rather than assuming a guard.
--
--  * The invoice is generated by the SYSTEM from the partner's final estimation,
--    not hand-keyed by an admin. admin_review_invoice can send it back, but it
--    cannot invent amounts — that is what makes "auto generated by system" true.
--
--  * Invoice numbers come from a sequence, so they are gapless per month and
--    safe under concurrency.
-- ═══════════════════════════════════════════════════════════════════════════════

-- ─── 1. Payment providers: configured, not hard-coded ─────────────────────────
-- Preparing for Midtrans, Xendit and manual transfer simultaneously. Provider
-- API keys are NOT stored here — they live in the edge function's secrets. This
-- row holds only what the app and the RPCs need to decide and to display.
CREATE TABLE IF NOT EXISTS public.payment_config (
  id                       INTEGER PRIMARY KEY CHECK (id = 1),
  online_enabled           BOOLEAN NOT NULL DEFAULT false,
  primary_provider         TEXT NOT NULL DEFAULT 'none'
                           CHECK (primary_provider IN ('midtrans', 'xendit', 'none')),
  fallback_provider        TEXT NOT NULL DEFAULT 'none'
                           CHECK (fallback_provider IN ('midtrans', 'xendit', 'none')),
  mode                     TEXT NOT NULL DEFAULT 'sandbox'
                           CHECK (mode IN ('sandbox', 'production')),
  manual_transfer_enabled  BOOLEAN NOT NULL DEFAULT true,
  -- [{"bank":"BCA","account_number":"...","account_holder":"PT Revive ..."}]
  bank_accounts            JSONB NOT NULL DEFAULT '[]'::jsonb,
  currency                 TEXT NOT NULL DEFAULT 'IDR',
  -- Seconds the customer gets to pay before the invoice expires.
  payment_window_hours     INTEGER NOT NULL DEFAULT 24,
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.payment_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.payment_config ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage payment config" ON public.payment_config;
CREATE POLICY "Admins manage payment config" ON public.payment_config
  FOR ALL TO authenticated
  USING (public.is_master_admin())
  WITH CHECK (public.is_master_admin());

-- ─── 2. Final estimation (the new form) ───────────────────────────────────────
-- One active submission per job. Superseding is allowed before release, because
-- a workshop that mis-keyed an amount needs to correct it; after release the
-- invoice is a document the customer may already have seen.
CREATE TABLE IF NOT EXISTS public.partner_final_estimations (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_id              UUID NOT NULL REFERENCES public.repair_jobs(id) ON DELETE CASCADE,
  partner_id          UUID REFERENCES public.partners(id) ON DELETE SET NULL,
  initial_cost        NUMERIC,                 -- snapshot of what the customer was quoted
  final_cost          NUMERIC NOT NULL CHECK (final_cost > 0),
  note                TEXT,
  -- [{panel, initial_cost, final_cost, severity, note}]
  panels              JSONB NOT NULL DEFAULT '[]'::jsonb,
  status              TEXT NOT NULL DEFAULT 'submitted'
                      CHECK (status IN ('submitted', 'superseded')),
  submitted_by        UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_final_estimations_job
  ON public.partner_final_estimations (job_id, created_at DESC);

-- At most one live submission per job.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_final_estimation_active
  ON public.partner_final_estimations (job_id)
  WHERE status = 'submitted';

DROP TRIGGER IF EXISTS set_final_estimations_updated_at ON public.partner_final_estimations;
CREATE TRIGGER set_final_estimations_updated_at
  BEFORE UPDATE ON public.partner_final_estimations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.partner_final_estimations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Parties read final estimations" ON public.partner_final_estimations;
CREATE POLICY "Parties read final estimations" ON public.partner_final_estimations
  FOR SELECT TO authenticated
  USING (
    public.is_master_admin()
    OR EXISTS (
      SELECT 1 FROM public.repair_jobs rj
       WHERE rj.id = partner_final_estimations.job_id
         AND (
           rj.customer_id = auth.uid()
           OR public.has_partner_membership(rj.partner_id,
                ARRAY['owner','mechanic','staff']::membership_role[])
         )
    )
  );

-- Writes go through partner_submit_final_estimation() only.
DROP POLICY IF EXISTS "Workshop members write final estimations" ON public.partner_final_estimations;
CREATE POLICY "Workshop members write final estimations" ON public.partner_final_estimations
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_master_admin()
    OR EXISTS (
      SELECT 1 FROM public.repair_jobs rj
       WHERE rj.id = partner_final_estimations.job_id
         AND public.has_partner_membership(rj.partner_id,
              ARRAY['owner','mechanic','staff']::membership_role[])
    )
  );

-- ─── 3. Invoices ──────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS public.invoice_number_seq;

CREATE OR REPLACE FUNCTION public.next_invoice_number()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_seq INTEGER;
BEGIN
  v_seq := nextval('public.invoice_number_seq');
  RETURN 'INV-' || to_char(now(), 'YYYYMM') || '-' || lpad(v_seq::TEXT, 5, '0');
END;
$function$;

CREATE TABLE IF NOT EXISTS public.invoices (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_number        TEXT NOT NULL UNIQUE,
  job_id                UUID NOT NULL REFERENCES public.repair_jobs(id) ON DELETE CASCADE,
  customer_id           UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  partner_id            UUID REFERENCES public.partners(id) ON DELETE SET NULL,
  estimation_id         UUID REFERENCES public.partner_final_estimations(id) ON DELETE SET NULL,

  initial_estimation_cost NUMERIC,             -- what the customer was originally quoted
  final_cost            NUMERIC NOT NULL CHECK (final_cost > 0),
  currency              TEXT NOT NULL DEFAULT 'IDR',
  line_items            JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- draft              generated from the final estimation, not yet checked
  -- awaiting_release   admin has checked it; customer cannot see it yet
  -- released           sent to the customer (mailer + WhatsApp); job is 3_inspected
  -- approved           customer accepted; awaiting payment
  -- declined           customer refused; job cancelled, partner notified
  -- paid               payment confirmed; job is 4_paid
  -- cancelled          withdrawn before release
  -- superseded         replaced by a corrected invoice
  status                TEXT NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','awaiting_release','released',
                                          'approved','declined','paid','cancelled','superseded')),

  generated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  checked_at            TIMESTAMPTZ,
  released_at           TIMESTAMPTZ,
  approved_at           TIMESTAMPTZ,
  declined_at           TIMESTAMPTZ,
  paid_at               TIMESTAMPTZ,
  expires_at            TIMESTAMPTZ,

  checked_by            UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  released_by           UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  decline_reason        TEXT,
  admin_note            TEXT,

  payment_method        TEXT
                        CHECK (payment_method IS NULL OR
                               payment_method IN ('midtrans','xendit','manual_transfer')),
  payment_reference     TEXT,          -- provider transaction id / bank reference
  payment_proof_keys    TEXT[],        -- storage keys for a manual-transfer slip

  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_invoices_job ON public.invoices (job_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON public.invoices (customer_id, created_at DESC);

-- One live invoice per job: a superseded or cancelled one does not block a new one.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_invoice_live_per_job
  ON public.invoices (job_id)
  WHERE status NOT IN ('superseded', 'cancelled');

DROP TRIGGER IF EXISTS set_invoices_updated_at ON public.invoices;
CREATE TRIGGER set_invoices_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Parties read invoices" ON public.invoices;
CREATE POLICY "Parties read invoices" ON public.invoices
  FOR SELECT TO authenticated
  USING (
    public.is_master_admin()
    -- The customer sees an invoice only once it has been released to them.
    OR (customer_id = auth.uid() AND status NOT IN ('draft','awaiting_release','cancelled'))
    OR public.has_partner_membership(partner_id, ARRAY['owner','mechanic','staff']::membership_role[])
  );

-- All writes go through the RPCs below.
DROP POLICY IF EXISTS "Admins write invoices" ON public.invoices;
CREATE POLICY "Admins write invoices" ON public.invoices
  FOR ALL TO authenticated
  USING (public.is_master_admin())
  WITH CHECK (public.is_master_admin());

-- ─── 4. Partner submits the final estimation → invoice auto-generated ─────────
CREATE OR REPLACE FUNCTION public.partner_submit_final_estimation(
  p_job_id      UUID,
  p_final_cost  NUMERIC,
  p_panels      JSONB DEFAULT '[]'::jsonb,
  p_note        TEXT  DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_job        RECORD;
  v_role       TEXT;
  v_partner_id UUID;
  v_est_id     UUID;
  v_inv_id     UUID;
  v_inv_no     TEXT;
  v_panels     JSONB := COALESCE(p_panels, '[]'::jsonb);
BEGIN
  v_role       := (auth.jwt() -> 'app_metadata' ->> 'role')::TEXT;
  v_partner_id := (auth.jwt() -> 'app_metadata' ->> 'partner_id')::UUID;

  SELECT * INTO v_job FROM public.repair_jobs WHERE id = p_job_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Job not found.');
  END IF;

  -- Workshop members who may price work, or an admin standing in for one.
  IF v_role <> 'master_admin' THEN
    IF v_role NOT IN ('partner_mechanic', 'partner_staff') THEN
      RETURN jsonb_build_object('success', false,
        'error', 'Only workshop staff can submit a final estimation.');
    END IF;
    IF v_job.partner_id IS DISTINCT FROM v_partner_id
       AND NOT public.has_partner_membership(v_job.partner_id,
             ARRAY['owner','mechanic','staff']::membership_role[]) THEN
      RETURN jsonb_build_object('success', false,
        'error', 'This job is not assigned to your workshop.');
    END IF;
  END IF;

  -- The car must be physically in the bay: a final price is only meaningful once
  -- the damage has actually been inspected.
  IF v_job.status <> '5_admitted' THEN
    RETURN jsonb_build_object('success', false, 'error', format(
      'Final estimation can only be submitted after the vehicle is admitted. Current status: %s',
      v_job.status));
  END IF;

  IF p_final_cost IS NULL OR p_final_cost <= 0 THEN
    RETURN jsonb_build_object('success', false,
      'error', 'Final cost must be a positive number.');
  END IF;

  -- Correcting a typo supersedes the previous submission rather than duplicating.
  IF EXISTS (SELECT 1 FROM public.partner_final_estimations
              WHERE job_id = p_job_id AND status = 'submitted') THEN
    IF EXISTS (SELECT 1 FROM public.invoices
                WHERE job_id = p_job_id AND status NOT IN ('draft','superseded','cancelled')) THEN
      RETURN jsonb_build_object('success', false,
        'error', 'The invoice for this job has already been released; contact an admin to correct it.');
    END IF;
    UPDATE public.partner_final_estimations
       SET status = 'superseded'
     WHERE job_id = p_job_id AND status = 'submitted';
    UPDATE public.invoices
       SET status = 'superseded'
     WHERE job_id = p_job_id AND status IN ('draft','awaiting_release');
  END IF;

  INSERT INTO public.partner_final_estimations
    (job_id, partner_id, initial_cost, final_cost, note, panels, submitted_by, status)
  VALUES
    (p_job_id, v_job.partner_id, v_job.initial_estimation_cost, p_final_cost,
     p_note, v_panels, auth.uid(), 'submitted')
  RETURNING id INTO v_est_id;

  -- The invoice is generated here, by the system, from the submitted figures.
  v_inv_no := public.next_invoice_number();

  INSERT INTO public.invoices
    (invoice_number, job_id, customer_id, partner_id, estimation_id,
     initial_estimation_cost, final_cost, line_items, status, generated_at)
  VALUES
    (v_inv_no, p_job_id, v_job.customer_id, v_job.partner_id, v_est_id,
     v_job.initial_estimation_cost, p_final_cost,
     COALESCE(v_panels, '[]'::jsonb) ||
       jsonb_build_array(jsonb_build_object(
         'label', 'Total', 'amount', p_final_cost)),
     'draft', now())
  RETURNING id INTO v_inv_id;

  PERFORM public.notify(
    'invoice_generated',
    'Estimasi Akhir Diterima',
    'Estimasi akhir untuk pekerjaan ini sudah dikirim dan sedang diperiksa oleh tim Revive.',
    p_job_id, 'admin');

  RETURN jsonb_build_object(
    'success', true,
    'estimation_id', v_est_id,
    'invoice_id', v_inv_id,
    'invoice_number', v_inv_no,
    'initial_cost', v_job.initial_estimation_cost,
    'final_cost', p_final_cost,
    'delta', CASE WHEN v_job.initial_estimation_cost IS NULL THEN NULL
                  ELSE p_final_cost - v_job.initial_estimation_cost END,
    'invoice_status', 'draft'
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.partner_submit_final_estimation(UUID, NUMERIC, JSONB, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.partner_submit_final_estimation(UUID, NUMERIC, JSONB, TEXT) TO authenticated;

-- ─── 5. Admin checks the job / sends back (the "admin check job" step) ────────
CREATE OR REPLACE FUNCTION public.admin_review_invoice(
  p_invoice_id UUID,
  p_action     TEXT,          -- 'check' (draft → awaiting_release) | 'send_back'
  p_note       TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_inv RECORD;
BEGIN
  IF NOT public.is_master_admin() THEN
    RETURN jsonb_build_object('success', false,
      'error', 'Only a platform admin can review an invoice.');
  END IF;

  IF p_action NOT IN ('check', 'send_back') THEN
    RETURN jsonb_build_object('success', false,
      'error', format('Unknown action: %s', p_action));
  END IF;

  SELECT * INTO v_inv FROM public.invoices WHERE id = p_invoice_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice not found.');
  END IF;

  IF p_action = 'check' THEN
    IF v_inv.status <> 'draft' THEN
      RETURN jsonb_build_object('success', false,
        'error', format('Only a draft invoice can be checked. Current status: %s', v_inv.status));
    END IF;
    UPDATE public.invoices
       SET status = 'awaiting_release', checked_at = now(),
           checked_by = auth.uid(), admin_note = COALESCE(p_note, admin_note)
     WHERE id = p_invoice_id;
    RETURN jsonb_build_object('success', true, 'invoice_status', 'awaiting_release');

  ELSE
    -- Sending back returns it to the workshop by voiding the draft; the partner
    -- then submits corrected figures and a fresh invoice is generated.
    IF v_inv.status <> 'awaiting_release' THEN
      RETURN jsonb_build_object('success', false,
        'error', format('Only a checked invoice can be sent back. Current status: %s', v_inv.status));
    END IF;
    UPDATE public.invoices
       SET status = 'superseded', admin_note = COALESCE(p_note, admin_note)
     WHERE id = p_invoice_id;
    UPDATE public.partner_final_estimations
       SET status = 'superseded'
     WHERE id = v_inv.estimation_id;

    PERFORM public.notify(
      'invoice_sent_back',
      'Estimasi Perlu Diperbaiki',
      COALESCE(p_note, 'Estimasi akhir perlu diperbaiki. Silakan kirim ulang melalui dashboard.'),
      v_inv.job_id, 'partner');

    RETURN jsonb_build_object('success', true, 'invoice_status', 'superseded');
  END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public.admin_review_invoice(UUID, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_review_invoice(UUID, TEXT, TEXT) TO authenticated;

-- ─── 6. Admin releases the invoice to the customer ────────────────────────────
-- This is the step that puts the job at 3_inspected: the existing status machine
-- already treats 3_inspected as "invoice issued, awaiting payment".
CREATE OR REPLACE FUNCTION public.admin_release_invoice(p_invoice_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_inv      RECORD;
  v_cfg      RECORD;
  v_deadline TIMESTAMPTZ;
BEGIN
  IF NOT public.is_master_admin() THEN
    RETURN jsonb_build_object('success', false,
      'error', 'Only a platform admin can release an invoice.');
  END IF;

  SELECT * INTO v_inv FROM public.invoices WHERE id = p_invoice_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice not found.');
  END IF;

  IF v_inv.status <> 'awaiting_release' THEN
    RETURN jsonb_build_object('success', false, 'error', format(
      'Only a checked invoice can be released. Current status: %s', v_inv.status));
  END IF;

  SELECT * INTO v_cfg FROM public.payment_config WHERE id = 1;
  v_deadline := now() + make_interval(hours => COALESCE(v_cfg.payment_window_hours, 24));

  UPDATE public.invoices
     SET status = 'released', released_at = now(), released_by = auth.uid(),
         expires_at = v_deadline
   WHERE id = p_invoice_id;

  -- Move the job only if it is still in the bay; re-releasing after a correction
  -- must not drag a job backwards.
  UPDATE public.repair_jobs
     SET status = '3_inspected', status_changed_at = now()
   WHERE id = v_inv.job_id AND status = '5_admitted';

  -- The status trigger already notifies the customer; this adds the amounts,
  -- which the generic status message cannot know.
  PERFORM public.notify(
    'invoice_released_detail',
    'Invoice ' || v_inv.invoice_number || ' Diterbitkan',
    format('Total perbaikan Anda: Rp %s. Silakan tinjau dan setujui invoice di aplikasi sebelum %s.',
           to_char(v_inv.final_cost, 'FM999G999G999G999'),
           to_char(v_deadline, 'DD Mon YYYY HH24:MI')),
    v_inv.job_id, 'customer',
    jsonb_build_object('invoice_id', p_invoice_id, 'invoice_number', v_inv.invoice_number,
                       'final_cost', v_inv.final_cost));

  RETURN jsonb_build_object(
    'success', true, 'invoice_status', 'released',
    'invoice_number', v_inv.invoice_number, 'expires_at', v_deadline);
END;
$function$;

REVOKE ALL ON FUNCTION public.admin_release_invoice(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_release_invoice(UUID) TO authenticated;

-- ─── 7. Admin admission (Case 1: Revive receives the car) ────────────────────
-- Case 1 had no real action — only a raw status override in a dropdown. This
-- gives it the same shape as the partner path, but attributed to an admin.
CREATE OR REPLACE FUNCTION public.admin_admit_vehicle(
  p_job_id UUID,
  p_note   TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_job RECORD;
BEGIN
  IF NOT public.is_master_admin() THEN
    RETURN jsonb_build_object('success', false,
      'error', 'Only a platform admin can admit a vehicle.');
  END IF;

  SELECT * INTO v_job FROM public.repair_jobs WHERE id = p_job_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Job not found.');
  END IF;

  IF v_job.status <> '3_booked' THEN
    RETURN jsonb_build_object('success', false, 'error', format(
      'Only a booked job can be admitted. Current status: %s', v_job.status));
  END IF;

  UPDATE public.repair_jobs
     SET status = '5_admitted', status_changed_at = now()
   WHERE id = p_job_id;

  -- The status trigger notifies customer and workshop; admins get the audit line.
  PERFORM public.notify(
    'vehicle_admitted_by_revive',
    'Kendaraan Diterima oleh Revive',
    COALESCE(p_note, 'Kendaraan sudah diterima di titik layanan Revive dan menunggu pemeriksaan.'),
    p_job_id, 'admin');

  RETURN jsonb_build_object('success', true, 'new_status', '5_admitted');
END;
$function$;

REVOKE ALL ON FUNCTION public.admin_admit_vehicle(UUID, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_admit_vehicle(UUID, TEXT) TO authenticated;

-- ─── 8. Customer approves or declines the invoice ────────────────────────────
-- Decline cancels the job (customer_cancel_job already permits 3_inspected) and
-- tells the workshop to arrange immediate hand-back.
CREATE OR REPLACE FUNCTION public.customer_respond_to_invoice(
  p_invoice_id UUID,
  p_approve    BOOLEAN,
  p_reason     TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_inv RECORD;
BEGIN
  SELECT * INTO v_inv FROM public.invoices WHERE id = p_invoice_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice not found.');
  END IF;

  IF v_inv.customer_id IS DISTINCT FROM auth.uid()
     AND NOT public.is_master_admin() THEN
    RETURN jsonb_build_object('success', false,
      'error', 'You can only respond to your own invoice.');
  END IF;

  IF v_inv.status <> 'released' THEN
    RETURN jsonb_build_object('success', false, 'error', format(
      'This invoice is not awaiting your decision. Current status: %s', v_inv.status));
  END IF;

  IF p_approve THEN
    UPDATE public.invoices
       SET status = 'approved', approved_at = now()
     WHERE id = p_invoice_id;

    PERFORM public.notify(
      'invoice_approved',
      'Invoice Disetujui',
      format('Invoice %s sudah Anda setujui. Silakan lanjutkan ke pembayaran.',
             v_inv.invoice_number),
      v_inv.job_id, 'customer');

    PERFORM public.notify(
      'invoice_approved_partner',
      'Invoice Disetujui Pelanggan',
      'Pelanggan menyetujui invoice. Menunggu pembayaran sebelum perbaikan dimulai.',
      v_inv.job_id, 'partner');

    RETURN jsonb_build_object('success', true, 'invoice_status', 'approved');

  ELSE
    UPDATE public.invoices
       SET status = 'declined', declined_at = now(), decline_reason = p_reason
     WHERE id = p_invoice_id;

    -- Cancel the job and free its booked slot. Mirrors customer_cancel_job()'s
    -- own gate (pre-payment statuses only) so the two cannot disagree.
    DELETE FROM public.partner_booked_slots WHERE job_id = v_inv.job_id;
    UPDATE public.repair_jobs
       SET status = '0_cancelled', status_changed_at = now()
     WHERE id = v_inv.job_id AND status IN ('1_intake','2_estimated','3_booked','3_inspected');

    PERFORM public.notify(
      'invoice_declined_partner',
      'Invoice Ditolak Pelanggan',
      'Pelanggan menolak invoice. Hubungi pelanggan untuk menjadwalkan pengembalian kendaraan.',
      v_inv.job_id, 'partner',
      jsonb_build_object('reason', p_reason));

    PERFORM public.notify(
      'invoice_declined_admin',
      'Invoice Ditolak Pelanggan',
      COALESCE(p_reason, 'Pelanggan menolak invoice.'),
      v_inv.job_id, 'admin',
      jsonb_build_object('reason', p_reason));

    RETURN jsonb_build_object('success', true, 'invoice_status', 'declined',
                              'job_status', '0_cancelled');
  END IF;
END;
$function$;

REVOKE ALL ON FUNCTION public.customer_respond_to_invoice(UUID, BOOLEAN, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.customer_respond_to_invoice(UUID, BOOLEAN, TEXT) TO authenticated;

-- ─── 9. Payment confirmed (gateway webhook, or admin verifying a transfer) ────
CREATE OR REPLACE FUNCTION public.invoice_mark_paid(
  p_invoice_id  UUID,
  p_method      TEXT,
  p_reference   TEXT  DEFAULT NULL,
  p_proof_keys  TEXT[] DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_inv RECORD;
BEGIN
  -- Only a platform admin may confirm by hand. A gateway webhook calls this as
  -- service_role, which bypasses RLS but still lands here, so the check is
  -- written to allow that path explicitly.
  IF NOT public.is_master_admin()
     AND current_user NOT IN ('service_role', 'postgres', 'supabase_admin') THEN
    RETURN jsonb_build_object('success', false,
      'error', 'Only a platform admin or the payment provider may confirm payment.');
  END IF;

  IF p_method NOT IN ('midtrans', 'xendit', 'manual_transfer') THEN
    RETURN jsonb_build_object('success', false,
      'error', format('Unknown payment method: %s', p_method));
  END IF;

  SELECT * INTO v_inv FROM public.invoices WHERE id = p_invoice_id FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invoice not found.');
  END IF;

  -- Accept `released` too: a customer may pay straight from the invoice without
  -- tapping approve first, and refusing real money for a missing click would be
  -- the wrong call.
  IF v_inv.status NOT IN ('released', 'approved') THEN
    RETURN jsonb_build_object('success', false, 'error', format(
      'This invoice cannot be paid from status %s.', v_inv.status));
  END IF;

  UPDATE public.invoices
     SET status = 'paid', paid_at = now(),
         payment_method = p_method,
         payment_reference = COALESCE(p_reference, payment_reference),
         payment_proof_keys = COALESCE(p_proof_keys, payment_proof_keys)
   WHERE id = p_invoice_id;

  -- Repair may begin: this is the only route to 4_paid.
  UPDATE public.repair_jobs
     SET status = '4_paid', status_changed_at = now()
   WHERE id = v_inv.job_id AND status = '3_inspected';

  RETURN jsonb_build_object(
    'success', true, 'invoice_status', 'paid',
    'invoice_number', v_inv.invoice_number,
    'job_id', v_inv.job_id, 'job_status', '4_paid');
END;
$function$;

REVOKE ALL ON FUNCTION public.invoice_mark_paid(UUID, TEXT, TEXT, TEXT[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.invoice_mark_paid(UUID, TEXT, TEXT, TEXT[]) TO authenticated;

-- ─── 10. Read helpers for the apps ────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_invoice_for_job(p_job_id UUID)
RETURNS JSONB
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE(jsonb_agg(x ORDER BY x.created_at DESC), '[]'::jsonb)
    FROM (
      SELECT i.id, i.invoice_number, i.status, i.initial_estimation_cost,
             i.final_cost, i.currency, i.line_items, i.created_at,
             i.released_at, i.expires_at, i.paid_at, i.decline_reason,
             i.payment_method,
             CASE WHEN i.initial_estimation_cost IS NULL THEN NULL
                  ELSE i.final_cost - i.initial_estimation_cost END AS delta,
             (SELECT jsonb_build_object('submitted_at', e.created_at, 'note', e.note,
                                        'panels', e.panels)
                FROM public.partner_final_estimations e
               WHERE e.job_id = i.job_id AND e.status = 'submitted'
               LIMIT 1) AS final_estimation
        FROM public.invoices i
       WHERE i.job_id = p_job_id
    ) x;
$function$;

REVOKE ALL ON FUNCTION public.get_invoice_for_job(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_invoice_for_job(UUID) TO authenticated;

-- ─── 11. Verification ─────────────────────────────────────────────────────────
WITH checks(ord, chk, got, want) AS (
  SELECT 1, 'tbl partner_final_estimations',
    (SELECT count(*)::text FROM information_schema.tables
      WHERE table_schema='public' AND table_name='partner_final_estimations'), '1'
  UNION ALL SELECT 2, 'tbl invoices',
    (SELECT count(*)::text FROM information_schema.tables
      WHERE table_schema='public' AND table_name='invoices'), '1'
  UNION ALL SELECT 3, 'tbl payment_config',
    (SELECT count(*)::text FROM information_schema.tables
      WHERE table_schema='public' AND table_name='payment_config'), '1'
  UNION ALL SELECT 4, 'fn partner_submit_final_estimation',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='partner_submit_final_estimation'), '1'
  UNION ALL SELECT 5, 'fn admin_review_invoice',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='admin_review_invoice'), '1'
  UNION ALL SELECT 6, 'fn admin_release_invoice',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='admin_release_invoice'), '1'
  UNION ALL SELECT 7, 'fn admin_admit_vehicle',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='admin_admit_vehicle'), '1'
  UNION ALL SELECT 8, 'fn customer_respond_to_invoice',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='customer_respond_to_invoice'), '1'
  UNION ALL SELECT 9, 'fn invoice_mark_paid',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='invoice_mark_paid'), '1'
  UNION ALL SELECT 10, 'fn get_invoice_for_job',
    (SELECT count(*)::text FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='public' AND p.proname='get_invoice_for_job'), '1'
  UNION ALL SELECT 11, 'invoice number sequence',
    (SELECT count(*)::text FROM pg_class WHERE relkind='S' AND relname='invoice_number_seq'), '1'
  UNION ALL SELECT 12, 'one live invoice per job enforced',
    (SELECT count(*)::text FROM pg_indexes
      WHERE schemaname='public' AND indexname='uniq_invoice_live_per_job'), '1'
  UNION ALL SELECT 13, 'payment providers prepared (midtrans+xendit allowed)',
    (SELECT (pg_get_constraintdef(oid) LIKE '%midtrans%'
             AND pg_get_constraintdef(oid) LIKE '%xendit%'
             AND pg_get_constraintdef(oid) LIKE '%manual_transfer%')::text
       FROM pg_constraint WHERE conname='invoices_payment_method_check'), 'true'
  UNION ALL SELECT 14, 'repair_jobs statuses NOT extended',
    (SELECT (pg_get_constraintdef(oid) NOT LIKE '%approved%'
             AND pg_get_constraintdef(oid) NOT LIKE '%awaiting_release%')::text
       FROM pg_constraint WHERE conname='repair_jobs_status_check'), 'true'
)
SELECT CASE WHEN got = want THEN 'PASS' ELSE '*** FAIL ***' END AS result, chk, got, want
FROM checks ORDER BY ord;
